print(3)
print(3>2)
print(3>4)
print(3==3)
print(3!=4)  #3 4 ta asamanada yannai ema nisa true we.
print(3!=3)
#print(3=3)
print("Hasaranga")
print('Hasaranga')#namak print karana kota udu koma demiya uthuya
#print('hasaranga's house')
print("hasaranga's house")
print('he said"I came"')
print(34+12)
print(34-12)
print(12*3)
print(12/4)
print(12%4) #  %-modulus (lesa hadunwai)
print(12%5)
print('3')
print('3*4') # ' me magin kiyanne laba di ethi deya print karana lesai.
print(3*4)